name: teambalancer
description: "Draw fair teams."
publish_to: "none"
version: 0.1.0+3

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  app_links: ^6.0.0
  calc: ^0.2.1
  flutter_svg: ^2.0.7
  intl: ^0.18.1
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.1
  share_plus: ^9.0.0
  flutter_svg_test: ^1.0.1
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  build_runner: ^2.4.5
  json_serializable: ^6.7.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/skills/
    - assets/sports/

flutter_launcher_icons:
  android: true
  ios: true
  image_path_ios: "assets/ICON-1.jpg"
  image_path: "assets/ICON-1.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/ICON-1.png"
  web:
    generate: true
    image_path: "assets/ICON-1.jpg"
