name: teambalancer
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  calc: ^0.2.1
  intl: ^0.18.1
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  build_runner: ^2.4.5
  json_serializable: ^6.7.0

flutter:
  uses-material-design: true
  generate: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/ICON-1.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/ICON-1.png"
  web:
    generate: true
    image_path: "assets/ICON-1.jpg"
